version: '3'
services:
  app:
    container_name: filestash
    image: 80d508a5cecc
    restart: always
    environment:
      - APPLICATION_URL=https://docs.optimuscore.cloud
    #- GDRIVE_CLIENT_ID=<gdrive_client>
    #- GDRIVE_CLIENT_SECRET=<gdrive_secret>
    #- DROPBOX_CLIENT_ID=<dropbox_key>
      - ONLYOFFICE_URL=<onlyoffice_url>
      - CANARY=true
    ports:
      - "8334:8334"
    volumes:
      - filestash_b:/app/data/state/
    networks:
      - app_net

  onlyoffice:
    container_name: filestash_oods
    image: onlyoffice/documentserver:7.1
    ports:
      - "7080:80"
      - "8443:443"
    networks:
      - app_net
    restart: unless-stopped

networks:
  app_net:
    external: true
volumes:
    filestash_b: {}
